[BranchTime팀] UserDetailView 구현
wecode-bootcamp-korea/33-2nd-BranchTime-backend pull request #10
Opened 2022-06-11 11:43 UTC by nicholas019

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- [BranchTime팀] UserDetailView 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
[구현내역]
1. 로그인으로 인해 생성된 토큰을 이용해 User DB에서 필요한 유저정보를 제공
2. Author DB의 user_id column에 토큰에서 디코딩한 id값이 존제할경우 Author 정보를 제공

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-06-13 01:39 UTC, lordmyshepherd commented on users/views.py
> +                    }
코드가 중복되는데 하나로 합칠 수 있을까요?

2022-06-13 02:48 UTC, nicholas019 commented on users/views.py
> +                    }
합치는 방법을 고려안했던건아닌데 곰곰히 생각해보고 주위에 동료들과함께 해결했습니다.. 아주 기본적인 딕셔너리의 기능을 제가 잠시 잊고있었습니다...

2022-06-14 05:15 UTC, lordmyshepherd requested changes

2022-06-14 05:15 UTC, lordmyshepherd commented on users/views.py
> +                user_detail['career']      = user.author.career
```python
class UserDetailView(View):
    @login_decorator
    def get(self, request):
        user = request.user

        result = {
            "id"              : user.id,
            "name"            : user.name,
            "description"     : user.introduction,
            "avatar"          : user.thumbnail,
            "subscriber"      : user.subscription.all().count(),
            "interestedAuthor": user.interestedauthor_set.all().count(),
            "author"          : {
                "description" : user.author.introduction if user.author else None,
                "career"      : user.author.career if user.author else None
            }
        }
       
        return JsonResponse({"result" : result}, status = 200)
```

2022-06-14 06:57 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-06-14 06:57 UTC, merged